// Константы для категорий модификаций оружия

export const MODIFICATION_CATEGORIES = {
  RECEIVER: 'Ресивер',
  BARREL: 'Ствол',
  STOCK: 'Ложа',
  SIGHT: 'Прицел',
  MUZZLE: 'Дуло',
  MAGAZINE: 'Магазин',
  GRIP: 'Рукоять'
};

// Русские названия категорий для отображения
export const CATEGORY_NAMES = {
  [MODIFICATION_CATEGORIES.RECEIVER]: 'Ресивер',
  [MODIFICATION_CATEGORIES.BARREL]: 'Ствол',
  [MODIFICATION_CATEGORIES.STOCK]: 'Ложа',
  [MODIFICATION_CATEGORIES.SIGHT]: 'Прицел',
  [MODIFICATION_CATEGORIES.MUZZLE]: 'Дуло',
  [MODIFICATION_CATEGORIES.MAGAZINE]: 'Магазин',
  [MODIFICATION_CATEGORIES.GRIP]: 'Рукоять'
};

// Порядок отображения категорий
export const CATEGORY_ORDER = [
  MODIFICATION_CATEGORIES.RECEIVER,
  MODIFICATION_CATEGORIES.BARREL,
  MODIFICATION_CATEGORIES.STOCK,
  MODIFICATION_CATEGORIES.SIGHT,
  MODIFICATION_CATEGORIES.MUZZLE,
  MODIFICATION_CATEGORIES.MAGAZINE,
  MODIFICATION_CATEGORIES.GRIP
]; 